// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBN104U7dhjGNdwDqYRSuMS4Mi7LHVtUfA',
    appId: '1:172309981110:web:65702177639e659647c317',
    messagingSenderId: '172309981110',
    projectId: 'campus-2e40e',
    authDomain: 'campus-2e40e.firebaseapp.com',
    databaseURL: 'https://campus-2e40e-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'campus-2e40e.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCm1WpvezWKtH_HH5BauzwmLhVhfszyKew',
    appId: '1:172309981110:android:40044b4fa6bdc9a747c317',
    messagingSenderId: '172309981110',
    projectId: 'campus-2e40e',
    databaseURL: 'https://campus-2e40e-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'campus-2e40e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCbsfGrS0YThY6c4H_wCeOQjOcaTKwrOJ8',
    appId: '1:172309981110:ios:89b5daa83b82b46d47c317',
    messagingSenderId: '172309981110',
    projectId: 'campus-2e40e',
    databaseURL: 'https://campus-2e40e-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'campus-2e40e.firebasestorage.app',
    iosBundleId: 'com.example.secu',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCbsfGrS0YThY6c4H_wCeOQjOcaTKwrOJ8',
    appId: '1:172309981110:ios:89b5daa83b82b46d47c317',
    messagingSenderId: '172309981110',
    projectId: 'campus-2e40e',
    databaseURL: 'https://campus-2e40e-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'campus-2e40e.firebasestorage.app',
    iosBundleId: 'com.example.secu',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBN104U7dhjGNdwDqYRSuMS4Mi7LHVtUfA',
    appId: '1:172309981110:web:32daa6a6092d8dc847c317',
    messagingSenderId: '172309981110',
    projectId: 'campus-2e40e',
    authDomain: 'campus-2e40e.firebaseapp.com',
    databaseURL: 'https://campus-2e40e-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'campus-2e40e.firebasestorage.app',
  );
}
